
const LOGIN_RATE_LIMIT_WINDOW_SECONDS = parseInt(process.env.LOGIN_RATE_LIMIT_WINDOW_SECONDS || "100", 10); // Time window in seconds
const LOGIN_RATE_LIMIT_MAX_REQUESTS = parseInt(process.env.LOGIN_RATE_LIMIT_MAX_REQUESTS || "100", 10); // Max requests allowed per window

console.log(`LOGIN_RATE_LIMIT_WINDOW_SECONDS: `, LOGIN_RATE_LIMIT_WINDOW_SECONDS);
console.log(`LOGIN_RATE_LIMIT_MAX_REQUESTS: `, LOGIN_RATE_LIMIT_MAX_REQUESTS);

export const LoginRateLimiterValues = {
    WINDOW_SECONDS: LOGIN_RATE_LIMIT_WINDOW_SECONDS,
    MAX_REQUESTS: LOGIN_RATE_LIMIT_MAX_REQUESTS
};